/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemIntelligenceRouteImport } from './routes/system-intelligence'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeIntelligenceRouteImport } from './routes/knowledge-intelligence'
import { Route as GithubIntelligenceRouteImport } from './routes/github-intelligence'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicGithubCallbackRouteImport } from './routes/api/public/github.callback'
import { Route as ApiPublicGithubAuthorizeRouteImport } from './routes/api/public/github.authorize'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIntelligenceRoute = SystemIntelligenceRouteImport.update({
  id: '/system-intelligence',
  path: '/system-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIntelligenceRoute = KnowledgeIntelligenceRouteImport.update({
  id: '/knowledge-intelligence',
  path: '/knowledge-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubIntelligenceRoute = GithubIntelligenceRouteImport.update({
  id: '/github-intelligence',
  path: '/github-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGithubCallbackRoute = ApiPublicGithubCallbackRouteImport.update({
  id: '/api/public/github/callback',
  path: '/api/public/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGithubAuthorizeRoute =
  ApiPublicGithubAuthorizeRouteImport.update({
    id: '/api/public/github/authorize',
    path: '/api/public/github/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github-intelligence': typeof GithubIntelligenceRoute
  '/knowledge-intelligence': typeof KnowledgeIntelligenceRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/api/public/github/authorize': typeof ApiPublicGithubAuthorizeRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github-intelligence': typeof GithubIntelligenceRoute
  '/knowledge-intelligence': typeof KnowledgeIntelligenceRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/api/public/github/authorize': typeof ApiPublicGithubAuthorizeRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/chat': typeof ChatRoute
  '/docs': typeof DocsRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/github-intelligence': typeof GithubIntelligenceRoute
  '/knowledge-intelligence': typeof KnowledgeIntelligenceRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product': typeof ProductRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
  '/terms': typeof TermsRoute
  '/workflow': typeof WorkflowRoute
  '/api/public/github/authorize': typeof ApiPublicGithubAuthorizeRoute
  '/api/public/github/callback': typeof ApiPublicGithubCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/chat'
    | '/docs'
    | '/download'
    | '/forgot-password'
    | '/github-intelligence'
    | '/knowledge-intelligence'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/system-intelligence'
    | '/terms'
    | '/workflow'
    | '/api/public/github/authorize'
    | '/api/public/github/callback'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/app'
    | '/chat'
    | '/docs'
    | '/download'
    | '/forgot-password'
    | '/github-intelligence'
    | '/knowledge-intelligence'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/system-intelligence'
    | '/terms'
    | '/workflow'
    | '/api/public/github/authorize'
    | '/api/public/github/callback'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/chat'
    | '/docs'
    | '/download'
    | '/forgot-password'
    | '/github-intelligence'
    | '/knowledge-intelligence'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/product'
    | '/refunds'
    | '/reset-password'
    | '/signup'
    | '/system-intelligence'
    | '/terms'
    | '/workflow'
    | '/api/public/github/authorize'
    | '/api/public/github/callback'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRoute
  ChatRoute: typeof ChatRoute
  DocsRoute: typeof DocsRoute
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GithubIntelligenceRoute: typeof GithubIntelligenceRoute
  KnowledgeIntelligenceRoute: typeof KnowledgeIntelligenceRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductRoute: typeof ProductRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SystemIntelligenceRoute: typeof SystemIntelligenceRoute
  TermsRoute: typeof TermsRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiPublicGithubAuthorizeRoute: typeof ApiPublicGithubAuthorizeRoute
  ApiPublicGithubCallbackRoute: typeof ApiPublicGithubCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-intelligence': {
      id: '/system-intelligence'
      path: '/system-intelligence'
      fullPath: '/system-intelligence'
      preLoaderRoute: typeof SystemIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-intelligence': {
      id: '/knowledge-intelligence'
      path: '/knowledge-intelligence'
      fullPath: '/knowledge-intelligence'
      preLoaderRoute: typeof KnowledgeIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-intelligence': {
      id: '/github-intelligence'
      path: '/github-intelligence'
      fullPath: '/github-intelligence'
      preLoaderRoute: typeof GithubIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/callback': {
      id: '/api/public/github/callback'
      path: '/api/public/github/callback'
      fullPath: '/api/public/github/callback'
      preLoaderRoute: typeof ApiPublicGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/github/authorize': {
      id: '/api/public/github/authorize'
      path: '/api/public/github/authorize'
      fullPath: '/api/public/github/authorize'
      preLoaderRoute: typeof ApiPublicGithubAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRoute,
  ChatRoute: ChatRoute,
  DocsRoute: DocsRoute,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GithubIntelligenceRoute: GithubIntelligenceRoute,
  KnowledgeIntelligenceRoute: KnowledgeIntelligenceRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductRoute: ProductRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SystemIntelligenceRoute: SystemIntelligenceRoute,
  TermsRoute: TermsRoute,
  WorkflowRoute: WorkflowRoute,
  ApiPublicGithubAuthorizeRoute: ApiPublicGithubAuthorizeRoute,
  ApiPublicGithubCallbackRoute: ApiPublicGithubCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
